spring.application.name=Neo_bank_360_app

spring.datasource.url=jdbc:mysql://localhost:3306/neobank_db
spring.datasource.username=neobank_user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
